version: '3.9'

services:
  record_project:
    container_name: record_project
    image: jffhtchr/record_project:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=record_project_db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
    ports:
      - "${RECORD_PROJECT_PORT}:${RECORD_PROJECT_PORT}"
    depends_on:
      - record_project_db
    env_file: .env
  record_project_db:
    container_name: record_project_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${RECORD_PROJECT_DB_PORT}:${RECORD_PROJECT_DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
volumes:  
  pgdata: {}
